### ISSUE TITLE
Models don't need objects for each field

### ISSUE THREAD

**Issue by aric87** [danj707/fantasy-app#2]
You've got this: `position: {type: String,},` for most of the things in the models. If it's a simple structure (meaning, you're only giving it a type) you don't need to make it an object. So DEFschema can be: 

```
def_pid: {
        type: String,
        unique:true,
        required:true,
        },
    position: String,
    lname: String,
    fname: String,
    jersey: String,    
    real_team: String,
    height: String,
    weight: String,
    college: String,
```

**Comment by aric87** [comment]
in the Team schema, you have unique:false for the helmet. That's the default setting, so you can remove that

**Comment by aric87** [comment]
It looks like almost all your player models are the same. Consider simplifying that to have 1 model, and add a position field. The players that don't have links, or something else, can default to null (add default: null to the schema for those) and you can handle that on the front end (if null, don't show). That will make maintaining this easier, and, make it easier to simplify the routes mentioned in #1

**Comment by danj707** [comment]
Updated schemas to remove the 'false' flag since its the defauls

**Comment by danj707** [comment]
Updated schemas to convert objects to simple structure
